#!/usr/bin/env bash
# ============================================================
# CE VAULT — Cloud Agent local Supabase bootstrap (idempotent)
# Brings up a REAL local Supabase stack (Postgres + PostgREST + Kong),
# applies the repo schema/patches, grants + seeds dev data, and writes
# .env.local so the Next.js dev server talks to it.
#
# Safe to run on every boot: it detects existing state and only does
# what is missing. It never prints secrets and uses the well-known
# local-Supabase demo JWT secret (dev-only, not a production secret).
# ============================================================
set -uo pipefail

log() { echo "[cloud-supabase-up] $*"; }

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Local-Supabase default HS256 secret (deterministic dev keys; not a real secret)
LOCAL_JWT_SECRET="super-secret-jwt-token-with-at-least-32-characters-long"
SUPABASE_LOCAL_URL="http://127.0.0.1:54321"
DB_CONTAINER="supabase_db_workspace"

mint_keys() {
  node -e '
    const c = require("crypto");
    const secret = process.argv[1];
    const b64 = (o) => Buffer.from(typeof o === "string" ? o : JSON.stringify(o)).toString("base64url");
    const mk = (role) => {
      const h = b64({ alg: "HS256", typ: "JWT" });
      const now = Math.floor(Date.now() / 1000);
      const p = b64({ role, iss: "supabase-demo", iat: now, exp: now + 3600 * 24 * 3650 });
      const s = c.createHmac("sha256", secret).update(h + "." + p).digest("base64url");
      return `${h}.${p}.${s}`;
    };
    process.stdout.write(mk("anon") + " " + mk("service_role"));
  ' "$LOCAL_JWT_SECRET"
}

write_env_local() {
  local anon="$1" sr="$2"
  # Preserve a REAL remote .env.local, but overwrite placeholders and local configs.
  # A real remote has a supabase.co URL that is not localhost and not a template placeholder.
  if [ -f .env.local ] \
    && grep -qE 'NEXT_PUBLIC_SUPABASE_URL=https://[a-z0-9]+\.supabase\.co' .env.local \
    && ! grep -q "127.0.0.1:54321" .env.local \
    && ! grep -qiE 'xxxx|placeholder|your-|replace-' .env.local; then
    log ".env.local points at a real remote Supabase — leaving it untouched"
    return
  fi
  cat > .env.local <<EOF
# Auto-generated by scripts/cloud-supabase-up.sh — LOCAL DEV ONLY (gitignored)
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_LOCAL_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${anon}
SUPABASE_SECRET_KEY=${sr}
SUPABASE_SERVICE_ROLE_KEY=${sr}
DASHBOARD_PIN=000000
DASHBOARD_SESSION_SECRET=localdevsessionsecret0123456789abcdef0123456789
ALLOW_INSECURE_DEV_API=1
DEFAULT_SELL_RATE=35.5
DEFAULT_MARKET_RATE=34.8
OCR_AUTO_MIN=90
EOF
  log ".env.local written for local Supabase"
}

ensure_docker() {
  if docker info >/dev/null 2>&1; then return; fi
  log "starting docker daemon..."
  # Nested-VM networking fixes: let bridged container traffic bypass iptables
  sudo sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true
  sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
  sudo iptables-legacy -P FORWARD ACCEPT 2>/dev/null || true
  sudo nohup dockerd >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 30); do docker info >/dev/null 2>&1 && break; sleep 2; done
}

fix_docker_net() {
  sudo chmod 666 /var/run/docker.sock 2>/dev/null || true
  sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
  sudo iptables-legacy -P FORWARD ACCEPT 2>/dev/null || true
}

ensure_supabase() {
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^${DB_CONTAINER}\$"; then
    log "supabase already running"
    return
  fi
  log "starting supabase stack (this can take a few minutes on first boot)..."
  if ! supabase start >/tmp/supabase-start.log 2>&1; then
    log "retrying supabase start after clean stop..."
    supabase stop --no-backup >/dev/null 2>&1 || true
    supabase start >/tmp/supabase-start.log 2>&1 || { log "supabase start FAILED — see /tmp/supabase-start.log"; return 1; }
  fi
}

wait_for_db() {
  for _ in $(seq 1 60); do
    docker exec "$DB_CONTAINER" pg_isready -U postgres >/dev/null 2>&1 && return 0
    sleep 2
  done
  log "database did not become ready in time"
  return 1
}

apply_schema() {
  local has_admins
  has_admins="$(docker exec "$DB_CONTAINER" psql -U postgres -d postgres -tAc "select to_regclass('public.admins') is not null;" 2>/dev/null | tr -d '[:space:]')"
  if [ "$has_admins" != "t" ]; then
    log "applying schema.sql + patches..."
    docker cp supabase/schema.sql "$DB_CONTAINER":/tmp/schema.sql >/dev/null 2>&1 || true
    docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -v ON_ERROR_STOP=0 -f /tmp/schema.sql >/tmp/ce-schema.log 2>&1 || true
    for f in patch-v2 patch-v3 patch-v4-perf patch-v5 patch-v6 patch-v7 patch-v8 \
             patch-v9_add_live_message_fields patch-v10-production-safety \
             patch-v11-admin-console patch-v12-bot-metrics; do
      [ -f "supabase/$f.sql" ] || continue
      docker cp "supabase/$f.sql" "$DB_CONTAINER":/tmp/p.sql >/dev/null 2>&1 || true
      docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -v ON_ERROR_STOP=0 -f /tmp/p.sql >>/tmp/ce-schema.log 2>&1 || true
    done
  else
    log "schema already present"
  fi

  # Grants + dev seed — always run, fully idempotent.
  docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -v ON_ERROR_STOP=0 >/dev/null 2>&1 <<'SQL' || true
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant select on all tables in schema public to anon, authenticated;
grant execute on all functions in schema public to service_role, anon, authenticated;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant select on tables to anon, authenticated;
insert into admins (telegram_user_id, name, holding_usdt)
  values (123456789, 'Boss', 0)
  on conflict (telegram_user_id) do nothing;
insert into rates (sell_rate, market_usdt_rate)
  select 35.5, 34.8 where not exists (select 1 from rates);
SQL
  log "grants + dev seed applied"
}

main() {
  read -r ANON SR < <(mint_keys)
  write_env_local "$ANON" "$SR"

  ensure_docker
  fix_docker_net
  if ! ensure_supabase; then
    log "Supabase unavailable — dev server will still boot but data features need Supabase."
    exit 0
  fi
  wait_for_db || exit 0
  apply_schema
  log "local Supabase ready at ${SUPABASE_LOCAL_URL}"
}

main "$@"
